# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(verbose_name='upload date')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
