# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_auto_20170410_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'ordering': ['-upload file time']},
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='upload file',
            field=models.FileField(default='', upload_to='file/'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='upload file path',
            field=models.FilePathField(default='', path='file/'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='upload file time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
