# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0007_auto_20170413_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'ordering': ['-filename']},
        ),
        migrations.RenameField(
            model_name='uploadfile',
            old_name='upload file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='uploadfile',
            old_name='file name',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='uploadfile',
            old_name='upload file path',
            new_name='filepath',
        ),
        migrations.RenameField(
            model_name='uploadfile',
            old_name='upload file time',
            new_name='timestamp',
        ),
    ]
