# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0008_auto_20170413_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=100)),
            ],
        ),
    ]
