# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0010_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uploadfile',
            options={},
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='filepath',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='uploadfile',
            table='draw_uploadfile',
        ),
    ]
